Update README file with recent maven coordinates
mebigfatguy/fb-contrib pull request #345
Opened 2019-05-15 21:17 UTC by Dichotomia

2019-05-17 00:24 UTC, ThrawnCA requested changes
The Spotbugs Maven Plugin should use the `sb-contrib` artifact rather than `fb-contrib`.

2019-05-17 00:24 UTC, ThrawnCA commented on README.md
> +    <groupId>com.github.spotbugs</groupId>
This coordinate also appears on line 75.

2019-05-19 23:01 UTC, ThrawnCA requested changes

2019-05-19 23:01 UTC, ThrawnCA commented on README.md
>  com.mebigfatguy.fb-contrib, and the artifact ID is fb-contrib. Eg:
Starting from version 7.4.5, the SpotBugs Maven Plugin should use the `sb-contrib` artifact ID instead of `fb-contrib`.

2019-05-25 13:00 UTC, merged

2019-05-25 13:00 UTC, mebigfatguy commented
thanks